### ISSUE TITLE
All-1 can not contain the last tile anymore

### ISSUE THREAD

**Issue by Oliv4945** [Acklio/schc-over-lorawan#23]
Since we have 10 bytes tiles, it will not fit in SF10/US

**Comment by ivajloip** [comment]
Do we need to mandate this? While in US we might not be able to use it, in other regions it might lead to energy savings I believe. I agree that leaving it unspecified might require implementations to support it in cases where that is not needed, but I am not confident that we should remove this option...

**Comment by Oliv4945** [comment]
I discussed if with Laurent and Dominique today. It has to be specified in the profile.
Moreover I do prefer to restrict options that can lead to errors like we did for 8 bits ruleIds. But I do not know usual IETF position on that.

We can discuss it tomorrow if you want 😃

**Comment by arun1587** [comment]
The last tile can be smaller than the regular tile size and in this case, the all-1 shall still able to carry last tile. 
Sorry, if I missed understanding the problem statement correctly.

**Comment by Oliv4945** [comment]
@arun1587 

Dominique told us that this behavior MUST be selected in a profile, so an implementation cannot select one or another regarding the last payload size.
In SF10 US payload is 11 bytes, it is not enough for 4 bytes mic + 10 bytes (max tile size) + header. So the last tile MUST be carried by penultimate tile.

I made the change in 43960f6c95b29c2b8d5136d94f78686637bf60ab
